# Generated by Django 4.1.3 on 2022-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
