# Generated by Django 4.1.3 on 2022-11-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=200)),
                ('p_date', models.DateTimeField(verbose_name='data published')),
                ('p_body', models.TextField()),
                ('p_photo', models.ImageField(blank=True, upload_to='images/')),
                ('p_clicks', models.PositiveIntegerField(default=0, verbose_name='자유_조회수')),
                ('p_like_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='p_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comments', to='free.free')),
                ('p_parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='free.p_comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
